name: Github-Actions. github contexts.
on:
  push:
    branches:
      - task/github-action-context/github

jobs:
  FIRST-JOB:
    name: $${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event name is ${{ github.event_name }}."
      - run: echo "Brnach name is ${{ github.ref }}."