name: Push Any Branch.
on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event name is ${{ github.event_name }}."
      - run: echo "Brnach name is ${{ github.ref }}."

