name: Approve Pull Request.
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event name is ${{ github.event_name }}."
      - run: echo "Brnach name is ${{ github.ref }}."
