name: GitHub Actions for Java with maven.
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first step"
      - run: echo "Event name is ${{ github.event_name }}."
